# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe79427af7091173bb4b1839805768d0213fe343cffb72c7c159b16e8850d1755d10f9c72f97d2cc6af7a27243c17f05ababdf595fb42c25aafac1660140c9be

test:
  secret_key_base: 7edb58d160cf8b677e219218c7c1e633cfcb2bc7b4ba15474f08635a30c10b7a83184f09b6bceefc7d90cf364040459e45bd7bb0bb8c0c60c2075f0a90bb1380

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
